[package]
name = "libmodbus-rs"
version = "0.7.1"
authors = ["Stefan Müller <co@zzeroo.com>"]
readme = "README.md"
keywords = ["modbus", "libmodbus"]
documentation = "http://zzeroo.github.io/libmodbus-rs/libmodbus_rs/index.html"
repository = "https://github.com/zzeroo/libmodbus-rs.git"
homepage = "http://zzeroo.github.io/libmodbus-rs"
description = "C bindings to libmodbus"
license = "LGPL-2.1" # same as libmodbus
categories = ["api-bindings"]

[badges]
travis-ci = { repository = "zzeroo/libmodbus-rs" }
#appveyor = { repository = "zzeroo/libmodbus-rs" }

[dependencies]
libc = "0.2"
libmodbus-sys = { path = "libmodbus-sys", version = "0.7" }
rand = "0.3"
time = "0.1"

[dependencies.clap]
version = "2.24.2"
default-features = false
 # Cherry-pick the features you'd like to use
features = [ "color" ]

[dependencies.error-chain]
version = "0.11"
default-features = false
