[package]
name = "libmodbus-sys"
version = "0.2.1"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
links = "libmodbus"
build = "build.rs"
repository = "https://github.com/zzeroo/libmodbus-rs.git"
license = "LGPL-2.1"
description = "Native bindings to the libmodbus library"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"
