[package]

name = "libmodbus-sys"
version = "0.4.0"
authors = ["Stefan Müller <co@zzeroo.com>"]
links = "modbus"
build = "build.rs"
repository = "https://github.com/zzeroo/libmodbus-rs"
license = "LGPL-2.1"
description = "Native bindings to the libmodbus library"

[lib]
name = "libmodbus_sys"
path = "lib.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "^0.25"
gcc = "^0.3"
pkg-config = "^0.3"
